### ISSUE TITLE
installedMaps returning wrong list.

### ISSUE THREAD

**Issue by chitrank2050** [mattermoran/map_launcher#38]
Upon using the package I ran into an issue, on iOS the Apple maps application is not installed or disabled but the output of installedMaps contain 'apple maps'.

**Comment by mattermoran** [comment]
Hi. There's currently no way to check if Apple Maps has been removed from Home screen or not. Because it's not really being uninstalled and just hidden any method to check if it's present always returns true. You can see more here: https://stackoverflow.com/questions/39603120/how-to-check-if-apple-maps-is-installed
I will add this info in the README's known issues

**Comment by mattermoran** [comment]
Readme has been updated
