### ISSUE TITLE
Waypoint Not Working

### ISSUE THREAD

**Issue by ibrahim-demirci** [mattermoran/map_launcher#73]
Waypoint attribute work only google maps ( I try google maps, yandex navigator, yandex maps.

**Comment by mattermoran** [comment]
Hey. Yes, that's correct. I added a table in the README saying which maps support which features but it seems like the waypoints part is hidden because table is too wide :) I will also add comments in the dart code.
For supporting other maps I still gotta find time and research which maps allow waypoints (I think apple one does)
I'll leave a comment here when I have an update on that

**Comment by mattermoran** [comment]
The progress on waypoints will be tracked in #113
