### ISSUE TITLE
The title is not fully displayed on Google maps

### ISSUE THREAD

**Issue by Salmonberry** [mattermoran/map_launcher#85]
On IOS,when I add a title that includes')', the ')' and subsequent text in the title cannot be displayed.

**Comment by mattermoran** [comment]
In order to display the title on google maps, we have to construct the URL in a format like `q=lat,long(title)`. That works fine even with extra parentheses on Android but iOS is not able to process it correctly, unfortunately. 
It seems like it's the issue with google maps on iOS. Nothing this plugin can do.
On your side, you can just clean up the title to not include the parentheses.
